---
title: "Lab 01 - Hello R"
author: "AHMED ADNAN"
date: "1/27/2021"
output: html_document
---

University ID:2200000997 

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Lab Exercise

```
head(datasaurus_dozen)
```
head is return the firist or last of an object
```
summary(datasaurus_dozen)
```
used to produce result summaries of the results of various model fitting functions

```
View(datasaurus_dozen)
```
view give me three columns and numbers x and y


```{r}
 datasaurus_dozen %>%
 count(dataset) %>%
 print(13)
 ```
 
 ```{r}
 dino_data <- datasaurus_dozen %>%
 filter(dataset == "dino")
 
 ```
 ```{r}
 ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
geom_point()
 ```
 ```{r}
 dino_data %>%
 summarize(r = cor(x, y))
 ```
 ```{r}
 star_data <- datasaurus_dozen %>%
 filter(dataset == "star")
 
 ```
  ```{r}
 ggplot(data = star_data, mapping = aes(x = x, y = y)) +
geom_point()
 ```
  ```{r}
 star_data %>%
 summarize(r = cor(x, y))
 ```
 ```{r}
 circle_data <- datasaurus_dozen %>%
 filter(dataset == "circle")
 
 ```
  ```{r}
 ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
geom_point()
 ```
  ```{r}
 circle_data %>%
 summarize(r = cor(x, y))
 ```
 
 
 
 